### PR TITLE
add connection URL

### PR DESCRIPTION
**Pull request by michaelwittig**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by michaelwittig** [comment]
test

**Comment by michaelwittig** [comment]
test

**Comment by michaelwittig** [comment]
@andreaswittig what do you thin about outputting a "secret" ? see #5

**Comment by andreaswittig** [comment]
> @andreaswittig what do you thin about outputting a "secret" ? see #5

I don't think we should output a secret. What about using a `AWS::SecretsManager::Secret`?

**Pull request closed without merging**
