### PR TITLE
init

### PR DESCRIPTION
**Pull request by michaelwittig**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by michaelwittig** [comment]
based on this request https://community.cloudonaut.io/t/adding-new-resources-elasticache-redis-to-the-default-stack/136

**Comment by michaelwittig** [comment]
test

**Comment by michaelwittig** [comment]
test

**Review by andreaswittig — APPROVED** [review]
+1

**Comment by michaelwittig** [comment]
test

**Comment by michaelwittig** [comment]
test

**Review by andreaswittig — COMMENTED** [review]
+1

**Pull request merged**
